// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEW1rtsX2-uV197gGfRamibtwSMaogAXg',
    appId: '1:981215142203:web:404c8b925cc23e38ba971e',
    messagingSenderId: '981215142203',
    projectId: 'chat-app-588ee',
    authDomain: 'chat-app-588ee.firebaseapp.com',
    storageBucket: 'chat-app-588ee.appspot.com',
    measurementId: 'G-0HJ4DRH8SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSoFuxhSQ0j5xM2ZJUHAXu7QmvDXblNRI',
    appId: '1:981215142203:android:95ff21826b76e1d1ba971e',
    messagingSenderId: '981215142203',
    projectId: 'chat-app-588ee',
    storageBucket: 'chat-app-588ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefjjeZlE3HkGCBrOUQB_qqppyEOT3q48',
    appId: '1:981215142203:ios:5451545b17508147ba971e',
    messagingSenderId: '981215142203',
    projectId: 'chat-app-588ee',
    storageBucket: 'chat-app-588ee.appspot.com',
    iosClientId: '981215142203-as78otn2bihrmbqgdpr7fmhi3ai6gdh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBefjjeZlE3HkGCBrOUQB_qqppyEOT3q48',
    appId: '1:981215142203:ios:5451545b17508147ba971e',
    messagingSenderId: '981215142203',
    projectId: 'chat-app-588ee',
    storageBucket: 'chat-app-588ee.appspot.com',
    iosClientId: '981215142203-as78otn2bihrmbqgdpr7fmhi3ai6gdh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
